server:
  host: "127.0.0.1"
  port: "5000"
  debug-username: "debug"
  debug-password: "debug"
  upstream:
    active: yes
    override-root: yes
    locations:
      - url: "http://localhost:8080"
        endpoint: "/"

globals:
  s:
    value:
      value: "abc"
      type: "string"
    value2:
      value: "abc2"
      type: "string"
